### ISSUE TITLE
flutter小白，想请问怎么在ubuntu上安装这个软件

### ISSUE THREAD

**Issue by yuboona** [mapleafgo/clash-for-flutter#1]
你好，我对flutter开发出来的软件如何跑起来非常陌生，请问可以在readme中加一些ubuntu安装的教程么。或者可以贴一些你觉得有帮助的blog也可以。十分感谢！！

**Comment by fanlide** [comment]
@yuboona 如果仅仅想使用该软件，linux下下载appimage包，双击就可运行。如果想开发桌面端的flutter应用，可以看看readme中说的go-flutter，当然还可以用flutter官方的桌面版

**Comment by yuboona** [comment]
> @yuboona 如果仅仅想使用该软件，linux下下载appimage包，双击就可运行。如果想开发桌面端的flutter应用，可以看看readme中说的go-flutter，当然还可以用flutter官方的桌面版

非常感谢！
