### ISSUE TITLE
init error after start

### ISSUE THREAD

**Issue by Louis-J** [mapleafgo/clash-for-flutter#10]
OS: manjaro kde
output:
```
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":141.7674418604651,"monitorWidthMm":344,"monitorWidthSc":1920,"mscpi":141.7674418604651,"pixelRatio":0.8860465116279069,"ppsc":1,"windowWidthPx":904,"windowWidthSc":904}

(clash_for_flutter:95393): Gtk-WARNING **: 13:30:29.913: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
```
screen output: 显示"初始化失败"
other:
sometimes after restart it can start sucsessfully, but still display `go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'` error

**Comment by mapleafgo** [comment]
Please specify the version number

**Comment by Louis-J** [comment]
the version is v0.0.6-alpha, and i downloaded it from the release page

the version of libappindicator-gtk3 is 12.10.0.r296-1
the version of gtk3 is 1:3.24.28-1
but i think the dependencies have no problem

**Comment by mapleafgo** [comment]
This is issue for goflutter engine, but I haven't found it in other Linux.

**Comment by soHardToHaveAName** [comment]
> the version is v0.0.6-alpha, and i downloaded it from the release page
> 
> the version of libappindicator-gtk3 is 12.10.0.r296-1 the version of gtk3 is 1:3.24.28-1 but i think the dependencies have no problem
 
解决了吗？我也出现了一样的问题，初始化失败

**Comment by mapleafgo** [comment]
> > the version is v0.0.6-alpha, and i downloaded it from the release page
> > 
> > the version of libappindicator-gtk3 is 12.10.0.r296-1 the version of gtk3 is 1:3.24.28-1 but i think the dependencies have no problem
>  
> 解决了吗？我也出现了一样的问题，初始化失败

是初始化数据库下载失败，由于国内原因github的文件下载容易失败，我用了fastgit的镜像源，这镜像源最近换域名了...

**Comment by mapleafgo** [comment]
fastgit已经恢复了

**Comment by lxsy-xcy** [comment]
好像还是会出现初始化失败的问题
