### ISSUE TITLE
Please add support for special character

### ISSUE THREAD

**Issue by ningwang-arch** [mapleafgo/clash-for-flutter#12]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Error on line 902, column 11: Unexpected character.
    ╷
902 │     name: 🔰国外流量
    │           ^
    ╵
#0      Parser.parse (package:yaml/src/parser.dart:59)
#1      Loader._loadMapping (package:yaml/src/loader.dart:166)
#2      Loader._loadNode (package:yaml/src/loader.dart:89)
#3      Loader._loadSequence (package:yaml/src/loader.dart:143)
#4      Loader._loadNode (package:yaml/src/loader.dart:87)
#5      Loader._loadMapping (package:yaml/src/loader.dart:166)
#6      Loader._loadNode (package:yaml/src/loader.dart:89)
#7      Loader._loadDocument (package:yaml/src/loader.dart:65)
#8      Loader.load (package:yaml/src/loader.dart:57)
#9      loadYamlDocument (package:yaml/yaml.dart:69)
#10     loadYamlNode (package:yaml/yaml.dart:54)
#11     loadYaml (package:yaml/yaml.dart:41)
#12     _ConfigFileBase.start (package:clash_for_flutter/app/source/global_config.dart:167)
<asynchronous suspension>
#13     _ConfigFileBase.openProxy (package:clash_for_flutter/app/source/global_config.dart:179)
<asynchronous suspension>
#14     AsyncAction.run (package:mobx/src/api/async/async_action.dart:28)
<asynchronous suspension>

**Comment by mapleafgo** [comment]
This is [yaml](https://github.com/dart-lang/yaml/issues/53), waiting to fix it

**Comment by mapleafgo** [comment]
试试 [v0.0.7-alpha](https://github.com/mapleafgo/clash-for-flutter/releases/tag/v0.0.7-alpha)
