### ISSUE TITLE
初始化失败？

### ISSUE THREAD

**Issue by lxsy-xcy** [mapleafgo/clash-for-flutter#16]
下载之后，加载一段时间显示初始化失败

**Comment by mapleafgo** [comment]
由于[fastgit](https://github.com/FastGitORG/document)还是没有恢复，下载数据文件出错，看官方貌似永久切到 hub.fastgit.xyz 了。

**Comment by mapleafgo** [comment]
目前解决方法: 

手动下载数据文件[Country.mmdb](https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb)，然后放在下面系统对应的目录下

Linux: `~/.local/share/clash_for_flutter`

Windows: `~/AppData/Roaming/clash_for_flutter`

MacOS:

**Comment by lxsy-xcy** [comment]
好的，已解决
