### ISSUE TITLE
更新订阅后看不到节点

### ISSUE THREAD

**Issue by mdogwoop** [mapleafgo/clash-for-flutter#2]
更新之后代理页面还是一片空白，另外有没有兴趣给这个发布到aur里面（系统Arch linux，版本滚的最新版，就酱）

**Comment by mapleafgo** [comment]
Arch没有用过😅用的deepin，发布的话。暂时还没打算

**Comment by mapleafgo** [comment]
空白的问题是在Arch下吗？

**Comment by mdogwoop** [comment]
不知道，别的系统可能也会有？

**Comment by Sciroccogti** [comment]
之前我也遇到这个，好像是添加订阅后再更新订阅才能显示这样子。
