### ISSUE TITLE
跪求打包linux版本的

### ISSUE THREAD

**Issue by pengdaCN** [mapleafgo/clash-for-flutter#23]
跪求打包linux版本的，现在的releases上没有Linux版

**Comment by mapleafgo** [comment]
Linux 的没有环境了，之前的Arch滚坏了、、、
可以的话，你可以试着自己打包看看

**Comment by pengdaCN** [comment]
> 

好的，我试试

**Comment by mapleafgo** [comment]
专门写了个[开发打包文档](https://github.com/mapleafgo/clash-for-flutter#%E5%BC%80%E5%8F%91%E6%89%93%E5%8C%85%E8%AF%B4%E6%98%8E)，试着打包试试

**Comment by mapleafgo** [comment]
打了个zip包，其他格式的我还得调下环境
