### ISSUE TITLE
linux 平台 appimage运行报错

### ISSUE THREAD

**Issue by pengdaCN** [mapleafgo/clash-for-flutter#25]
在linux 平台运行报错
/tmp/.mount_clash_5KHdJM/clash_for_flutter: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory

**Comment by mapleafgo** [comment]
装下 `libayatana-appindicator3`

**Comment by mapleafgo** [comment]
不过我这边appimage报另外个错，你看看你依赖装好了能运行不

**Comment by mapleafgo** [comment]
加我微信帮我调下linux平台，与 github 同账号，谢谢

**Comment by pengdaCN** [comment]
> 加我微信帮我调下linux平台，与 github 同账号，谢谢

好，我试试
