### ISSUE TITLE
希望能增加 网速显示 和 按延迟排序 功能

### ISSUE THREAD

**Issue by Sciroccogti** [mapleafgo/clash-for-flutter#3]

**Comment by mapleafgo** [comment]
这个后期有打算支持，只是快过年了，最近精力有限。年后会加上的😅

**Comment by Sciroccogti** [comment]
那太好了！

顺便的话，还有 icon 是不是也有一点小问题呀？看起来有不少白边2333

![image](https://user-images.githubusercontent.com/32357397/104815583-64ff1a00-5850-11eb-8b09-48de50fec1d7.png)

**Comment by mapleafgo** [comment]
@Sciroccogti 这是之前随便找的图片转换…尴尬尴尬
