### ISSUE TITLE
macOS编译运行时动态库问题

### ISSUE THREAD

**Issue by wosika** [mapleafgo/clash-for-flutter#32]
`error: /Users/kale/dev/flutterProjects/clash-for-flutter/macos/Frameworks/libclash.dylib: No such file or directory (in target 'Runner' from project 'Runner')
`

已经根据readme中的流程运行了指令，运行时出现。

**Comment by mapleafgo** [comment]
需要移动下位置，项目根目录执行 `cp -f ./core/dist/libclash.dylib ./macos/Frameworks/libclash.dylib`
