### ISSUE TITLE
您好这是什么情况哈

### ISSUE THREAD

**Issue by niufuwei** [mapleafgo/clash-for-flutter#33]
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-000264A902F9401E }
{ platform:macOS, arch:x86_64, id:00006000-000264A902F9401E }
error: /Users/mac/Desktop/zero_mac_windows/macos/Frameworks/libclash.dylib: No such file or directory (in target 'Runner' from project 'Runner')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed

**Comment by niufuwei** [comment]
我是按照步骤一个一个来的

**Comment by mapleafgo** [comment]
#32

**Comment by mapleafgo** [comment]
我还是更新上readme吧

**Comment by niufuwei** [comment]
可以了，谢谢啊。可以价格tg吗@parker_2022

**Comment by niufuwei** [comment]
可以了，谢谢啊
