### ISSUE TITLE
能打包个直接跑ubuntu20.04的版本吗

### ISSUE THREAD

**Issue by lducsm** [mapleafgo/clash-for-flutter#39]
./clash_for_flutter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found.

要新版glibc呢，老麻烦了，起码得从2004开始支持吧，可别2204

**Comment by mapleafgo** [comment]
我改变了下actions的运行器，现在使用20.04构建的。你可以下载最新的构建包使用看看
