### ISSUE TITLE
大佬这个是什么核心

### ISSUE THREAD

**Issue by wisdomTechnologyIoT** [mapleafgo/clash-for-flutter#46]
该项目是clash.meta核心吗

**Comment by mapleafgo** [comment]
基于clash 1.18的

**Comment by helloworld-men** [comment]
> 基于clash 1.18的，tun是另外集成的

请问我可以自己替换为meta核心吗

**Comment by mapleafgo** [comment]
@helloworld-men 需要自己根据meta源码进行编译动态库。

另外移动端内核是单独做过处理才能用的，meta要改部分源码才行。

这些都需要你有一定golang知识才能行。

不必非要mate内核的，meta的源码我看过。里面增加了一些其他协议，且支持tun。但是那些协议一般都用不上。且mate内核打包下来20+M，clash只有几M
