### ISSUE TITLE
Exception: Unable to generate build files

### ISSUE THREAD

**Issue by Mahiro2211** [mapleafgo/clash-for-flutter#47]
我用的是Deepin V20 community 按照readme说的做了一遍
 flutter run -d linux
用这个命令等时候出现了这个错误，想请教一下是否是系统的问题呢？

**Comment by mapleafgo** [comment]
感觉像没有执行第二步

`dart run build_runner build --delete-conflicting-outputs`

截屏完整的报错呢

**Comment by Mahiro2211** [comment]
很抱歉我草率的提出啦这个issue
经过stackoverflow，我发现是Cmake的问题
安装完之后再执行 flutter clean 就好啦
感谢作者这么快的回复
