### ISSUE TITLE
Ubuntu 下 Clash 的配置文件在哪里？

### ISSUE THREAD

**Issue by Sciroccogti** [mapleafgo/clash-for-flutter#5]
查看源码可知应当在 `.local/share/clash_for_flutter/config.json`，但未能在该目录下找到。（其它文件倒是有

![image](https://user-images.githubusercontent.com/32357397/105159996-ad695100-5b4a-11eb-8522-7d7144fff78e.png)

**Comment by mapleafgo** [comment]
就是'cfm.json'

**Comment by mapleafgo** [comment]
我想起来了，确实应该还有个clash的配置文件。但这个文件暂时未用起来(设置部分还未写)，所以在应用中使用的默认值
