### ISSUE TITLE
ubuntu 初始化失败，某个socket 连接被拒绝

### ISSUE THREAD

**Issue by SunJon99** [mapleafgo/clash-for-flutter#51]
运行时出现错误提示如下：

![clash_for_flutter_error](https://github.com/mapleafgo/clash-for-flutter/assets/48266709/f1d79bfc-761b-4bc5-b10a-d2fafbd46f2e)

但是使用sudo可以正常运行，不知道为什么，希望大佬可以帮忙解惑

**Comment by mapleafgo** [comment]
是否配置了环境变量HTTP_PROXY的代理？配置上`export NO_PROXY=localhost,127.0.0.1`

**Comment by SunJon99** [comment]
谢谢，解决了

**Comment by SunJon99** [comment]
谢谢，解决了
