### ISSUE TITLE
怎么订阅，小白

### ISSUE THREAD

**Issue by crazysboy** [mapleafgo/clash-for-flutter#58]

**Comment by 99988209** [comment]
解决了吗？我也在问

**Comment by mapleafgo** [comment]
https://mapleafgo.github.io/clash-for-flutter/#/?id=%e8%ae%a2%e9%98%85

**Comment by 99988209** [comment]
> https://mapleafgo.github.io/clash-for-flutter/#/?id=%e8%ae%a2%e9%98%85

我知道是在哪个教程，但是我并没有订阅地址或者本地文件

**Comment by mapleafgo** [comment]
可以看看这个 [clashfree](https://github.com/aiboboxx/clashfree)
